export const GET_POKEMONSORIGINAL = "GET_POKEMONSORIGINAL";
export const GET_POKEMONS = "GET_POKEMONS";
export const GET_TYPES = "GET_TYPES";
export const SEARCH = "SEARCH";
export const SET_PAGES = "SET_PAGES";
export const SET_SELECTEDPAGE = "SET_SELECTEDPAGE";

export const DETAILED_POKEMON = "DETAILED_POKEMON";
