export const GET_POKEMONS = "GET_POKEMONS";
export const GET_TYPES = "GET_TYPES";
export const GET_EXACTPOKEMON = "GET_EXACTPOKEMON";
export const SET_PAGES = "SET_PAGES";
export const SET_SELECTEDPAGE = "SET_SELECTEDPAGE";
export const FILTER_POKEMON = "FILTER_POKEMON";
